import asyncio
import copy
import logging
import warnings
from typing import TYPE_CHECKING

from pywa.types.base_update import BaseUpdate

from . import _helpers as helpers
from . import errors, handlers, utils
from .handlers import (
    EncryptedFlowRequestType,
    Handler,
    RawUpdateHandler,
)
from .types import (
    ContinueHandling,
    RawUpdate,
    StopHandling,
)

_logger = logging.getLogger(__name__)


if TYPE_CHECKING:
    from pywa_async import WhatsApp

MAX_PROCESSED_UPDATES = 100_000


class Server:
    async def webhook_challenge_handler(
        self: "WhatsApp", vt: str, ch: str
    ) -> tuple[str, int]:
        """
        Handle the verification challenge from the webhook manually.

        - Use this function only if you are using a custom server (e.g. Django etc.).

        Args:
            vt: The verify token param (utils.HUB_VT).
            ch: The challenge param (utils.HUB_CH).

        Returns:
            A tuple containing the challenge and the status code.
        """
        return super().webhook_challenge_handler(vt=vt, ch=ch)

    async def webhook_update_validator(
        self: "WhatsApp", update: bytes, hmac_header: str | None
    ) -> tuple[str, int] | None:
        """
        Validate the incoming webhook update signature.

        Args:
            update: The incoming raw update from the webhook (bytes)
            hmac_header: The ``X-Hub-Signature-256`` header (to validate the signature, use ``utils.HUB_SIG`` for the key).

        Returns:
            A tuple of (error_message, status_code) if validation fails, otherwise None.
        """
        return super().webhook_update_validator(update=update, hmac_header=hmac_header)

    async def webhook_update_handler(
        self: "WhatsApp", update: bytes, hmac_header: None = None
    ) -> tuple[str, int]:
        """
        Handle the incoming update manually.

        - Use this function only if you are using a custom server (e.g. Django etc.).

        Args:
            update: The incoming raw update from the webhook (bytes)
            hmac_header: Deprecated. Use ``client.webhook_update_validator`` to validate the request first.

        Returns:
            A tuple containing the response and the status code.
        """
        if hmac_header is not None:
            warnings.warn(
                "The `hmac_header` argument in `webhook_update_handler` is deprecated and will be removed "
                "in a future version. Use `client.webhook_update_validator` to validate the request first.",
                DeprecationWarning,
                stacklevel=2,
            )
            error_response = await self.webhook_update_validator(update, hmac_header)
            if error_response:
                return error_response

        try:
            raw_update = RawUpdate(update, hmac_header=hmac_header)
        except (TypeError, ValueError):
            _logger.debug(
                "Webhook ('%s') received non-JSON data: %s",
                self._webhook_endpoint,
                update,
            )
            return "Bad Request", 400

        update_hash = hmac_header or str(hash(update))

        if self._skip_duplicate_updates:
            if update_hash in self._processed_updates:
                _logger.debug(
                    "Webhook ('%s') skipped duplicate update: %s",
                    self._webhook_endpoint,
                    update_hash,
                )
                return "ok", 200

            self._processed_updates[update_hash] = None

            if len(self._processed_updates) > MAX_PROCESSED_UPDATES:
                self._processed_updates.popitem(last=False)

        await self._call_handlers(raw_update)

        return "ok", 200

    def _register_flow_callback_wrapper(
        self: "WhatsApp",
        callback_wrapper: handlers.FlowRequestCallbackWrapper,
    ) -> handlers.FlowRequestCallbackWrapper:
        """Register the flow callback wrapper to the server."""
        match self._server_type:
            case utils.CustomServerType.FLASK:
                if not helpers.is_installed("asgiref"):  # flask[async]
                    raise ValueError(
                        "Flask with ASGI is required to handle incoming updates asynchronously. Please install "
                        """the `asgiref` package (`pip install "flask[async]"` / `pip install "asgiref"`)"""
                    )

                import flask

                @self._server.route(callback_wrapper._endpoint, methods=["POST"])
                @helpers.rename_func(f"('{callback_wrapper._endpoint}')")
                async def pywa_flow() -> tuple[str, int]:
                    """Automatically generated by pywa to handle incoming flow requests."""
                    return await callback_wrapper.handle_async(flask.request.json)

            case utils.CustomServerType.FASTAPI:
                import fastapi

                @self._server.post(callback_wrapper._endpoint)
                @helpers.rename_func(f"('{callback_wrapper._endpoint}')")
                async def pywa_flow(
                    flow_req: EncryptedFlowRequestType,
                ) -> fastapi.Response:
                    """Automatically generated by pywa to handle incoming flow requests."""
                    response, status_code = await callback_wrapper.handle_async(
                        flow_req
                    )
                    return fastapi.Response(
                        content=response,
                        status_code=status_code,
                    )

        return callback_wrapper

    async def _call_handlers(self: "WhatsApp", raw_update: RawUpdate) -> None:
        """Call the handlers for the given update."""
        try:
            try:
                handler_type = self._get_handler_type(raw_update)
            except (KeyError, ValueError, TypeError, IndexError):
                (_logger.error if self._validate_updates else _logger.debug)(
                    "Webhook ('%s') received unexpected update%s: %s",
                    self._webhook_endpoint,
                    " (Enable `validate_updates` to ignore updates with invalid data)"
                    if not self._validate_updates
                    else "",
                    raw_update,
                )
                handler_type = None

            if handler_type is None:
                return
            try:
                constructed_update: BaseUpdate = self._handlers_to_updates[
                    handler_type
                ].from_update(client=self, update=raw_update)
                if await self._process_listener(constructed_update):
                    return
                await self._invoke_callbacks(handler_type, constructed_update)
            except Exception:
                _logger.exception("Failed to construct update: %s", raw_update)
        finally:
            # Always call raw update handler last
            await self._call_raw_update_handler(raw_update)

    async def _call_raw_update_handler(self: "WhatsApp", update: RawUpdate) -> None:
        """Invoke the raw update handler."""
        await self._invoke_callbacks(RawUpdateHandler, update)

    async def _invoke_callbacks(
        self: "WhatsApp", handler_type: type[Handler], update: BaseUpdate | RawUpdate
    ) -> None:
        """Process and call registered handlers for the update."""
        for handler in self._handlers[handler_type]:
            try:
                handled = await handler.ahandle(self, update)
            except StopHandling:
                break
            except ContinueHandling:
                continue
            except Exception:
                handled = True
                _logger.exception(
                    "An error occurred while '%s' was handling an update",
                    handler._callback.__name__,
                )
            if handled and not self._continue_handling:
                break

    async def _process_listener(self: "WhatsApp", update: BaseUpdate) -> bool:
        """Process and answer a listener if present."""
        if not (listener_identifiers := update.listener_identifiers):
            return False
        for identifier in listener_identifiers:
            listener = self._listeners.get(identifier)
            if listener is not None:
                break
        else:
            return False

        try:
            if await listener.apply_filters(self, update):
                listener.set_result(update)
                return not self._continue_handling
            elif await listener.apply_cancelers(self, update):
                listener.cancel(update)
                return not self._continue_handling
            else:
                return False  # if no filters or cancelers matched, continue handling
        except ContinueHandling:
            return False
        except StopHandling:
            return True
        except Exception as e:
            listener.set_exception(e)

        return not self._continue_handling

    def _register_callback_url(
        self: "WhatsApp",
    ) -> None:
        """
        This is a non-blocking function that registers the callback URL.
        It must be called after the server is running so that the challenge can be verified.
        """
        loop = asyncio.new_event_loop()
        api = copy.copy(self.api)
        api._session = self._httpx_client(  # TODO: copy the session properly
            timeout=api._session.timeout,
            base_url=api._session.base_url,
            headers=api._session.headers,
        )

        try:
            match self._callback_url_scope:
                case utils.CallbackURLScope.APP:
                    app_access_token = loop.run_until_complete(
                        api.get_app_access_token(
                            client_id=self._app_id, client_secret=self._app_secret
                        )
                    )
                    res = loop.run_until_complete(
                        api.set_app_callback_url(
                            app_id=self._app_id,
                            access_token=app_access_token["access_token"],
                            callback_url=self._callback_url,
                            verify_token=self._verify_token,
                            fields=tuple(self._webhook_fields),
                        )
                    )
                case utils.CallbackURLScope.WABA:
                    res = loop.run_until_complete(
                        api.set_waba_alternate_callback_url(
                            waba_id=self.waba_id,
                            override_callback_uri=self._callback_url,
                            verify_token=self._verify_token,
                        )
                    )
                case utils.CallbackURLScope.PHONE:
                    res = loop.run_until_complete(
                        api.set_phone_alternate_callback_url(
                            override_callback_uri=self._callback_url,
                            verify_token=self._verify_token,
                            phone_id=self.phone_id,
                        )
                    )
                case _:
                    raise ValueError("Invalid callback URL scope")

            if not res["success"]:
                raise RuntimeError("Failed to register callback URL.")
            _logger.info(
                "Callback URL '%s' registered successfully", self._callback_url
            )
        except errors.WhatsAppError as e:
            raise RuntimeError(
                f"Failed to register callback URL '{self._callback_url}'. if you are using a slow/custom server, you can "
                "increase the delay using the `webhook_challenge_delay` parameter when initializing the WhatsApp client."
            ) from e
